

const BlogData = [

    {
       
        heading: "Food To Eat For Prediabetes",
        info: <p> &emsp; &emsp; Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id semper risus in hendrerit gravida rutrum. Vivamus arcu felis bibendum ut tristique et egestas quis. Semper quis lectus nulla at volutpat diam. Semper risus in hendrerit gravida. Maecenas sed enim ut sem viverra aliquet eget. Habitant morbi tristique senectus et netus et malesuada fames. Sed libero enim sed faucibus turpis in eu. Pellentesque massa placerat duis ultricies lacus sed turpis tincidunt id. Ac auctor augue mauris augue neque gravida in fermentum. Fames ac turpis egestas integer eget aliquet nibh praesent. Volutpat ac tincidunt vitae semper quis lectus nulla at volutpat. Scelerisque in dictum non consectetur a erat nam at lectus. Sed cras ornare arcu dui vivamus arcu felis. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque.
        <br/><br/> &emsp; &emsp; Donec ultrices tincidunt arcu non sodales neque sodales. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Feugiat in fermentum posuere urna nec. Et malesuada fames ac turpis egestas sed. At in tellus integer feugiat scelerisque varius morbi. Et pharetra pharetra massa massa ultricies mi quis hendrerit. In aliquam sem fringilla ut morbi tincidunt augue interdum. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Mi ipsum faucibus vitae aliquet nec. Purus gravida quis blandit turpis cursus.
        <br/><br/> &emsp; &emsp; Interdum velit euismod in pellentesque massa placerat. Nullam non nisi est sit. Enim blandit volutpat maecenas volutpat. Aliquam sem fringilla ut morbi tincidunt augue interdum velit. Id interdum velit laoreet id donec ultrices tincidunt arcu. Elit ullamcorper dignissim cras tincidunt lobortis feugiat. Mollis nunc sed id semper risus in hendrerit. Eget magna fermentum iaculis eu. Risus pretium quam vulputate dignissim suspendisse in est ante. Feugiat in fermentum posuere urna. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Suspendisse sed nisi lacus sed viverra tellus. Aliquam etiam erat velit scelerisque in dictum non consectetur a. Senectus et netus et malesuada fames ac turpis egestas integer. Ut diam quam nulla porttitor massa id neque aliquam. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque.
        Tristique senectus et netus et malesuada fames. Neque viverra justo nec ultrices dui sapien. Nibh venenatis cras sed felis eget velit aliquet sagittis. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Malesuada fames ac turpis egestas maecenas. Dui sapien eget mi proin sed libero enim sed. Amet consectetur adipiscing elit pellentesque. Sit amet luctus venenatis lectus magna. Dictum fusce ut placerat orci.</p>,
        link: "/blogdescription1"
      },

    {
      heading: "My Top 10 Tips On How To Eat Mindfully",
      info: <p>Lorem ipsum dolor sit amet, adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id semper risus in hendrerit gravida rutrum. Vivamus arcu felis bibendum ut tristique et egestas quis. Semper quis lectus nulla at volutpat diam. Semper risus in hendrerit gravida. Maecenas sed enim ut sem viverra aliquet eget. Habitant morbi tristique senectus et netus et malesuada fames. Sed libero enim sed faucibus turpis in eu. Pellentesque massa placerat duis ultricies lacus sed turpis tincidunt id. Ac auctor augue mauris augue neque gravida in fermentum. Fames ac turpis egestas integer eget aliquet nibh praesent. Volutpat ac tincidunt vitae semper quis lectus nulla at volutpat. Scelerisque in dictum non consectetur a erat nam at lectus. Sed cras ornare arcu dui vivamus arcu felis. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque.
      <br/><br/> &emsp; &emsp; Donec ultrices tincidunt arcu non sodales neque sodales. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Feugiat in fermentum posuere urna nec. Et malesuada fames ac turpis egestas sed. At in tellus integer feugiat scelerisque varius morbi. Et pharetra pharetra massa massa ultricies mi quis hendrerit. In aliquam sem fringilla ut morbi tincidunt augue interdum. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Mi ipsum faucibus vitae aliquet nec. Purus gravida quis blandit turpis cursus.
      <br/><br/> &emsp; &emsp; Interdum velit euismod in pellentesque massa placerat. Nullam non nisi est sit. Enim blandit volutpat maecenas volutpat. Aliquam sem fringilla ut morbi tincidunt augue interdum velit. Id interdum velit laoreet id donec ultrices tincidunt arcu. Elit ullamcorper dignissim cras tincidunt lobortis feugiat. Mollis nunc sed id semper risus in hendrerit. Eget magna fermentum iaculis eu. Risus pretium quam vulputate dignissim suspendisse in est ante. Feugiat in fermentum posuere urna. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Suspendisse sed nisi lacus sed viverra tellus. Aliquam etiam erat velit scelerisque in dictum non consectetur a. Senectus et netus et malesuada fames ac turpis egestas integer. Ut diam quam nulla porttitor massa id neque aliquam. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque.
      Tristique senectus et netus et malesuada fames. Neque viverra justo nec ultrices dui sapien. Nibh venenatis cras sed felis eget velit aliquet sagittis. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Malesuada fames ac turpis egestas maecenas. Dui sapien eget mi proin sed libero enim sed. Amet consectetur adipiscing elit pellentesque. Sit amet luctus venenatis lectus magna. Dictum fusce ut placerat orci.</p>,
      link: "/blogdescription2"
    },
  
    {
      heading: "5 Ways To Stay Healthy",
      info: <p>Lorem ipsum dolor sit amet, adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id semper risus in hendrerit gravida rutrum. Vivamus arcu felis bibendum ut tristique et egestas quis. Semper quis lectus nulla at volutpat diam. Semper risus in hendrerit gravida. Maecenas sed enim ut sem viverra aliquet eget. Habitant morbi tristique senectus et netus et malesuada fames. Sed libero enim sed faucibus turpis in eu. Pellentesque massa placerat duis ultricies lacus sed turpis tincidunt id. Ac auctor augue mauris augue neque gravida in fermentum. Fames ac turpis egestas integer eget aliquet nibh praesent. Volutpat ac tincidunt vitae semper quis lectus nulla at volutpat. Scelerisque in dictum non consectetur a erat nam at lectus. Sed cras ornare arcu dui vivamus arcu felis. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque.
      <br/><br/> &emsp; &emsp; Donec ultrices tincidunt arcu non sodales neque sodales. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Feugiat in fermentum posuere urna nec. Et malesuada fames ac turpis egestas sed. At in tellus integer feugiat scelerisque varius morbi. Et pharetra pharetra massa massa ultricies mi quis hendrerit. In aliquam sem fringilla ut morbi tincidunt augue interdum. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Mi ipsum faucibus vitae aliquet nec. Purus gravida quis blandit turpis cursus.
      <br/><br/> &emsp; &emsp; Interdum velit euismod in pellentesque massa placerat. Nullam non nisi est sit. Enim blandit volutpat maecenas volutpat. Aliquam sem fringilla ut morbi tincidunt augue interdum velit. Id interdum velit laoreet id donec ultrices tincidunt arcu. Elit ullamcorper dignissim cras tincidunt lobortis feugiat. Mollis nunc sed id semper risus in hendrerit. Eget magna fermentum iaculis eu. Risus pretium quam vulputate dignissim suspendisse in est ante. Feugiat in fermentum posuere urna. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Suspendisse sed nisi lacus sed viverra tellus. Aliquam etiam erat velit scelerisque in dictum non consectetur a. Senectus et netus et malesuada fames ac turpis egestas integer. Ut diam quam nulla porttitor massa id neque aliquam. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque.
      Tristique senectus et netus et malesuada fames. Neque viverra justo nec ultrices dui sapien. Nibh venenatis cras sed felis eget velit aliquet sagittis. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Malesuada fames ac turpis egestas maecenas. Dui sapien eget mi proin sed libero enim sed. Amet consectetur adipiscing elit pellentesque. Sit amet luctus venenatis lectus magna. Dictum fusce ut placerat orci.</p>,
      link: "/blogdescription3"
    },
  
    {
      heading: "20 Best Superfoods For Fast Weight Loss",
      info: <p>Lorem ipsum dolor sit amet, adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id semper risus in hendrerit gravida rutrum. Vivamus arcu felis bibendum ut tristique et egestas quis. Semper quis lectus nulla at volutpat diam. Semper risus in hendrerit gravida. Maecenas sed enim ut sem viverra aliquet eget. Habitant morbi tristique senectus et netus et malesuada fames. Sed libero enim sed faucibus turpis in eu. Pellentesque massa placerat duis ultricies lacus sed turpis tincidunt id. Ac auctor augue mauris augue neque gravida in fermentum. Fames ac turpis egestas integer eget aliquet nibh praesent. Volutpat ac tincidunt vitae semper quis lectus nulla at volutpat. Scelerisque in dictum non consectetur a erat nam at lectus. Sed cras ornare arcu dui vivamus arcu felis. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque.
      <br/><br/> &emsp; &emsp; Donec ultrices tincidunt arcu non sodales neque sodales. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Feugiat in fermentum posuere urna nec. Et malesuada fames ac turpis egestas sed. At in tellus integer feugiat scelerisque varius morbi. Et pharetra pharetra massa massa ultricies mi quis hendrerit. In aliquam sem fringilla ut morbi tincidunt augue interdum. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Mi ipsum faucibus vitae aliquet nec. Purus gravida quis blandit turpis cursus.
      <br/><br/> &emsp; &emsp; Interdum velit euismod in pellentesque massa placerat. Nullam non nisi est sit. Enim blandit volutpat maecenas volutpat. Aliquam sem fringilla ut morbi tincidunt augue interdum velit. Id interdum velit laoreet id donec ultrices tincidunt arcu. Elit ullamcorper dignissim cras tincidunt lobortis feugiat. Mollis nunc sed id semper risus in hendrerit. Eget magna fermentum iaculis eu. Risus pretium quam vulputate dignissim suspendisse in est ante. Feugiat in fermentum posuere urna. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Suspendisse sed nisi lacus sed viverra tellus. Aliquam etiam erat velit scelerisque in dictum non consectetur a. Senectus et netus et malesuada fames ac turpis egestas integer. Ut diam quam nulla porttitor massa id neque aliquam. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque.
      Tristique senectus et netus et malesuada fames. Neque viverra justo nec ultrices dui sapien. Nibh venenatis cras sed felis eget velit aliquet sagittis. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Malesuada fames ac turpis egestas maecenas. Dui sapien eget mi proin sed libero enim sed. Amet consectetur adipiscing elit pellentesque. Sit amet luctus venenatis lectus magna. Dictum fusce ut placerat orci.</p>,
      link: "/blogdescription4"
    }
  
  
  ]

  export default BlogData